force-app/main/default/objects/Tracking__c/Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking object for WO-000002</description>
    <label>Tracking</label>
    <nameField>
        <label>Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking__c/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <description>Date this tracking item was closed</description>
    <inlineHelpText>Date this tracking item was closed</inlineHelpText>
    <label>ClosedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <inlineHelpText>Description</inlineHelpText>
    <label>Description</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/IsTracked__c.field-meta.xml
<CustomField>
    <fullName>IsTracked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IsTracked (Default false)</description>
    <inlineHelpText>IsTracked (Default false)</inlineHelpText>
    <label>IsTracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracking Status</description>
    <inlineHelpText>Tracking Status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On_Hold</fullName>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Object to Track</description>
    <inlineHelpText>Type of Object to Track</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrackingListController.cls
/**
 * @description       : 
 * @author            : Ed Elliott
 * @group             : 
 * @last modified on  : 06-14-2023
 * @last modified by  : Ed Elliott 
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   06-14-2023   Ed Elliott   Initial Version
**/
public with sharing class TrackingListController {
    @AuraEnabled(cacheable = true)
    public static List<Tracking__c> getTrackingList() {
        return [SELECT Id, Name, ClosedDate__c,
                       CreatedBy.Name, CreatedDate,
                       Description__c, Status__c,
                       Type__c, LastModifiedBy.Name,
                       LastModifiedDate, IsTracked__c
                FROM Tracking__c
                ORDER BY CreatedDate DESC
                LIMIT 20];
    }
}