force-app/main/default/objects/Tracking__c/Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking object for WO-000002</description>
    <label>Tracking</label>
    <nameField>
        <label>Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking__c/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <description>Date this tracking item was closed</description>
    <inlineHelpText>Date this tracking item was closed</inlineHelpText>
    <label>ClosedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/IsTracked__c.field-meta.xml
<CustomField>
    <fullName>IsTracked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IsTracked (Default false)</description>
    <inlineHelpText>IsTracked (Default false)</inlineHelpText>
    <label>IsTracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracking Status</description>
    <inlineHelpText>Tracking Status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On_Hold</fullName>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tracking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Object to Track</description>
    <inlineHelpText>Type of Object to Track</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrackingListControllerTests.cls
/**
 * @description       : 
 * @author            : Ed Elliott
 * @group             : 
 * @last modified on  : 06-14-2023
 * @last modified by  : Ed Elliott
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   06-14-2023   Ed Elliott   Initial Version
**/
@isTest
public class TrackingListControllerTests {
    @TestSetup
    static void makeData() {
        List<Tracking__c> trackingList = new List<Tracking__c>();

        for (Integer i = 0; i < 10; i++) {
            Tracking__c t = new Tracking__c();
            t.Name = 'Test ' + i;
            t.IsTracked__c = true;
            t.Status__c = 'Open';
            t.ClosedDate__c = Date.today();
            t.Type__c = 'Account';
                       
            trackingList.add(t);
        }

        insert trackingList;
    }

    @isTest
    public static void testGetTrackingList() {
        List<Tracking__c> trackingList = TrackingListController.getTrackingList();

        System.assertEquals(10, trackingList.size());
    }
}