force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <description>Todo Object</description>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <description>Closed Date</description>
    <inlineHelpText>Closed Date</inlineHelpText>
    <label>ClosedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Todo__c/fields/IsTracked__c.field-meta.xml
<CustomField>
    <fullName>IsTracked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Tracked</description>
    <inlineHelpText>Is Tracked</inlineHelpText>
    <label>IsTracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type</description>
    <inlineHelpText>Type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TodoListControllerTests.cls
/**
 * @description       : 
 * @author            : Ed Elliott
 * @group             : 
 * @last modified on  : 06-19-2023
 * @last modified by  : Ed Elliott
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   06-14-2023   Ed Elliott   Initial Version
**/
@isTest
public class TodoListControllerTests {
    @TestSetup
    static void makeData() {
        List<Todo__c> todoList = new List<Todo__c>();

        for (Integer i = 0; i < 10; i++) {
            Todo__c t = new Todo__c();
            t.Name = 'Test ' + i;
            t.IsTracked__c = true;
            t.Status__c = 'Open';
            t.ClosedDate__c = Date.today();
            t.Type__c = 'Account';
                       
            todoList.add(t);
        }

        insert todoList;
    }

    @isTest
    public static void testGetTodoList() {
        List<Todo__c> todoList = TodoListController.getTodoList();

        System.assertEquals(10, todoList.size());
    }
}